--CUS.ChatMessageSummary--------------------------------------------------------

create table TpCUSmChatMessageSummary
(
	FId uuid primary key,
	FName varchar(50),
	U_RoomId varchar(50),
	U_ChatId varchar(50),
	U_UserId varchar(50),
	U_UserName varchar(50),
	U_AgentId varchar(50),
	U_SenderId varchar(50),
	U_SenderName varchar(50),
	U_SendTime timestamp,
	U_Content varchar(10000),
	U_Type varchar(20),
	U_AgentName varchar(50)
);

insert into TsUnit set FId='4806684c-e000-3135-6003-1961e9cb6d00', FCode='CUS.ChatMessageSummary', FName='聊天訊息彙整', FIcon='quicksilver/image/unit/New.gif', FBigIcon='quicksilver/image/unit/New-64.png', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='21e2754a-d586-4bfa-bebe-768f70b9148b', FOpenMode='System', FIsTreeStructure=0, FIsTreeCheckPrivilege=0, FMaxTreeLevel=null, FTreeDefaultExpandLevel=null, FIsSlaveUnit=0, FMasterUnitId=null, FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=0, FSupportAvatar=0, FSupportAlbum=0, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FApiEnabled=1, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TpCUSmChatMessageSummary', FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField=null, FHomeClassName='com.ai3.ecp.cus.chatmessagesummary.ChatMessageSummaryHome', FDaoClassName='com.ai3.ecp.cus.chatmessagesummary.dao.impl.ChatMessageSummaryDaoImpl', FServiceClassName='com.ai3.ecp.cus.chatmessagesummary.service.impl.ChatMessageSummaryServiceImpl', FActionClassName='com.ai3.ecp.cus.chatmessagesummary.action.impl.ChatMessageSummaryActionImpl', FApiClassName='com.ai3.ecp.cus.chatmessagesummary.api.impl.ChatMessageSummaryApiImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FEsDataSource='default', FEsIndex=null, FEsType='data', FEsDaoClassName=null, FTenantMode=null, FDescription='', FOpenViewPageCondition=null, FOpenViewPageFirst=null;

insert into TsField set FId='4806684c-e000-3135-6003-1961e9cb7620', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='FId',          FTitle='ID',         FType='InputBox-Key',     FSize=null,  FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FParentField=null, FEntityUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint=null, FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null, FMaskEnabled=null, FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=null, FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961e9cb7650', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='FName',        FTitle='名稱',       FType='InputBox-Text',    FSize=50,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961ea01bb80', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_AgentId',    FTitle='AgentId',    FType='InputBox-Text',    FSize=50,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961ea475a80', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_AgentName',  FTitle='AgentName',  FType='InputBox-Text',    FSize=50,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961e9e772b0', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_ChatId',     FTitle='ChatId',     FType='InputBox-Text',    FSize=50,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961ea1dd370', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_Content',    FTitle='Content',    FType='InputBox-Text',    FSize=10000, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961e9dbf6a0', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_RoomId',     FTitle='聊天室ID',   FType='InputBox-Text',    FSize=50,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961ea08c700', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_SenderId',   FTitle='SenderId',   FType='InputBox-Text',    FSize=50,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961ea0e2c70', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_SenderName', FTitle='SenderName', FType='InputBox-Text',    FSize=50,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961ea14a860', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_SendTime',   FTitle='SendTime',   FType='DateBox-DateTime', FSize=null,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961ea252ec0', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_Type',       FTitle='Type',       FType='InputBox-Text',    FSize=20,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961e9f1fb00', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_UserId',     FTitle='UserId',     FType='InputBox-Text',    FSize=50,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;
insert into TsField set FId='4806684c-e000-3135-6003-1961e9fb6320', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='U_UserName',   FTitle='UserName',   FType='InputBox-Text',    FSize=50,    FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null, FParentField=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FTitleWidth=null, FControlWidth=null, FControlWidthValue=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='',   FMaskEnabled=0,    FLeftNumberToShow=null, FRightNumberToShow=null, FRightLessNumberToShow=null, FEncrypted=0,    FSelectListFilterSqlExceedable=null, FSelectListFilterSql=null;

java setQueryFormFields('4806684c-e000-3135-6003-1961e9cb6d00', 'FName');
java setKeywordFields('4806684c-e000-3135-6003-1961e9cb6d00', 'FName');

insert into TsPage set FId='4806684c-e000-3135-6003-1961e9cb7a80', FName='聊天訊息彙整主列表',   FTitle='聊天訊息彙整列表', FCode='CUS.ChatMessageSummary.List',       FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/New.gif',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='CUS.ChatMessageSummary.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null, FGroupId=null;
insert into TsPage set FId='4806684c-e000-3135-6003-1961e9cb7b60', FName='聊天訊息彙整選擇列表', FTitle='聊天訊息彙整列表', FCode='CUS.ChatMessageSummary.SelectList', FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/New.gif',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='CUS.ChatMessageSummary.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null, FGroupId=null;
insert into TsPage set FId='4806684c-e000-3135-6003-1961e9cb7960', FName='聊天訊息彙整表單',     FTitle='表單',             FCode='CUS.ChatMessageSummary.Form',       FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EntityForm', FIcon='quicksilver/image/unit/Form.png', FUrl='quicksilver/page/template/EntityForm.jsp', FActionMethodName='CUS.ChatMessageSummary.prepareForm', FLoadHandler=null, FRelationId=null, FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FMasterUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FIsSlavePage=1, FIndex=1,    FFormColumnCount=null, FDialogWidth=null, FDialogHeight=500,  FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null, FGroupId=null;

--聊天訊息彙整主列表
insert into TsToolItem set FId='4806684c-e000-3135-6003-1961e9cb7ab0', FPageId='4806684c-e000-3135-6003-1961e9cb7a80', FCode='Add',     FName='新增',     FHint='新增一筆資料',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Add.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='4806684c-e000-3135-6003-1961e9cb7ae0', FPageId='4806684c-e000-3135-6003-1961e9cb7a80', FCode='Open',    FName='打開',     FHint='打開當前選中的資料。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='4806684c-e000-3135-6003-1961e9cb7b10', FPageId='4806684c-e000-3135-6003-1961e9cb7a80', FCode='Delete',  FName='刪除',     FHint='刪除當前選中的資料',                                   FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Delete.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doDelete';
insert into TsToolItem set FId='4806684c-e000-3135-6003-1961e9cb7b20', FPageId='4806684c-e000-3135-6003-1961e9cb7a80', FCode='Refresh', FName='重新整理', FHint='重新整理清單內容',                                     FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
insert into TsToolItem set FId='4806684c-e000-3135-6003-1961e9cb7b30', FPageId='4806684c-e000-3135-6003-1961e9cb7a80', FCode='Other',   FName=null,       FHint=null,                                                   FLabel=null, FType='ComboButton', FAlign='right', FIndex=5, FWidth=0, FIcon='quicksilver/image/16/Other.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='4806684c-e000-3135-6013-1961e9cb7b30', FToolItemId='4806684c-e000-3135-6003-1961e9cb7b30', FCode='Import',      FName='匯入',     FExpandMode='None', FIndex=1, FIcon='quicksilver/image/16/Import.png', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FEventHandler='EntityList.doImport';
insert into TsToolSubItem set FId='4806684c-e000-3135-6003-1961e9cb7b40', FToolItemId='4806684c-e000-3135-6003-1961e9cb7b30', FCode='ExcelExport', FName='匯出',     FExpandMode='None', FIndex=2, FIcon='quicksilver/image/16/Excel.png',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FEventHandler='EntityList.doExcelExport';
insert into TsToolSubItem set FId='4806684c-e000-3135-6003-1961e9cb7b50', FToolItemId='4806684c-e000-3135-6003-1961e9cb7b30', FCode='BillPrint',   FName='單據列印', FExpandMode='None', FIndex=3, FIcon='quicksilver/image/unit/Bill.png', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FEventHandler='EntityList.doBillPrint';

--聊天訊息彙整選擇列表
insert into TsToolItem set FId='4806684c-e000-3135-6003-1961e9cb7b70', FPageId='4806684c-e000-3135-6003-1961e9cb7b60', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='4806684c-e000-3135-6003-1961e9cb7b80', FPageId='4806684c-e000-3135-6003-1961e9cb7b60', FCode='Add',              FName='新增', FHint='新增一筆資料',                                         FLabel=null, FType='Button', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Add.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='4806684c-e000-3135-6013-1961e9cb7b80', FPageId='4806684c-e000-3135-6003-1961e9cb7b60', FCode='Open',             FName='打開', FHint='打開當前選中的資料。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

--聊天訊息彙整表單
insert into TsToolItem set FId='4806684c-e000-3135-6003-1961e9cb79c0', FPageId='4806684c-e000-3135-6003-1961e9cb7960', FCode='Save',  FName='保存', FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityForm.doSave';
insert into TsToolItem set FId='4806684c-e000-3135-6003-1961e9cb7a00', FPageId='4806684c-e000-3135-6003-1961e9cb7960', FCode='Other', FName=null,   FHint=null, FLabel=null, FType='ComboButton', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Other.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='4806684c-e000-3135-6003-1961e9cb7a40', FToolItemId='4806684c-e000-3135-6003-1961e9cb7a00', FCode='BillPrint', FName='單據列印', FExpandMode='None', FIndex=1, FIcon='quicksilver/image/unit/Bill.png', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FEventHandler='EntityForm.doBillPrint';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='Double', FId='4806684c-e000-3135-6003-1961e9cb81d0', FIndex=1, FName='預設', FPageId=null, FPlatform='Computer', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00';
java setFormFields('4806684c-e000-3135-6003-1961e9cb81d0', '基本資訊', '4806684c-e000-3135-6003-1961e9cb8410', null, 'FName,U_RoomId,U_ChatId,U_UserId,U_UserName,U_AgentId,U_SenderId,U_SenderName,U_SendTime,U_Content,U_Type,U_AgentName');

insert into TsList set FDefault=1, FId='4806684c-e000-3135-6003-1961e9cb87a0', FIndex=null, FMultiPage=1, FName='聊天訊息彙整列表',     FPageId=null,                                   FPlatform='Computer', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00';
insert into TsList set FDefault=0, FId='4806684c-e000-3135-6003-1961e9cb8800', FIndex=null, FMultiPage=1, FName='聊天訊息彙整選擇列表', FPageId='4806684c-e000-3135-6003-1961e9cb7b60', FPlatform='Computer', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00';
insert into TsList set FDefault=0, FId='4806684c-e000-3135-6003-1961e9cb8830', FIndex=null, FMultiPage=1, FName='聊天訊息彙整首頁列表', FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FPlatform='Computer', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00';
java setListFields('4806684c-e000-3135-6003-1961e9cb87a0', 'FName,U_RoomId,U_ChatId,U_UserId,U_UserName,U_AgentId,U_SenderId,U_SenderName,U_SendTime,U_Content,U_Type,U_AgentName');
java setListFields('4806684c-e000-3135-6003-1961e9cb8830', 'FName');
java setListFields('4806684c-e000-3135-6003-1961e9cb8800', 'FName');

insert into TsPrivilege set FId='4806684c-e000-3135-6003-1961e9cb8c30', FName='聊天訊息彙整刪除', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FModuleId='21e2754a-d586-4bfa-bebe-768f70b9148b', FPrivilegeTypeId='00000000-0000-0000-1005-000000000004', FUseExisting=0, FSourcePrivilegeId=null, FEditId='5992c3d2-0b4a-478c-bbfa-2089819ad575', FIsSystemLevel=0, FIndex=null;
insert into TsPrivilege set FId='4806684c-e000-3135-6003-1961e9cb8c10', FName='聊天訊息彙整查看', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FModuleId='21e2754a-d586-4bfa-bebe-768f70b9148b', FPrivilegeTypeId='00000000-0000-0000-1005-000000000002', FUseExisting=0, FSourcePrivilegeId=null, FEditId='5992c3d2-0b4a-478c-bbfa-2089819ad575', FIsSystemLevel=0, FIndex=null;
insert into TsPrivilege set FId='4806684c-e000-3135-6003-1961e9cb8c20', FName='聊天訊息彙整修改', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FModuleId='21e2754a-d586-4bfa-bebe-768f70b9148b', FPrivilegeTypeId='00000000-0000-0000-1005-000000000003', FUseExisting=0, FSourcePrivilegeId=null, FEditId='5992c3d2-0b4a-478c-bbfa-2089819ad575', FIsSystemLevel=0, FIndex=null;
insert into TsPrivilege set FId='4806684c-e000-3135-6003-1961e9cb8be0', FName='聊天訊息彙整新增', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FModuleId='21e2754a-d586-4bfa-bebe-768f70b9148b', FPrivilegeTypeId='00000000-0000-0000-1005-000000000001', FUseExisting=0, FSourcePrivilegeId=null, FEditId='5992c3d2-0b4a-478c-bbfa-2089819ad575', FIsSystemLevel=0, FIndex=null;

insert into TsQuerySchema set FId='4806684c-e000-3135-6003-1961e9cb8c50', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='全部聊天訊息彙整',     FType='condition',  FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=1, FUpdateTime=null, FOriginSchemaId=null, FParentId=null;
insert into TsQuerySchema set FId='4806684c-e000-3135-6003-1961e9cb8c70', FUnitId='4806684c-e000-3135-6003-1961e9cb6d00', FName='聊天訊息彙整我的最愛', FType='collection', FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=3, FUpdateTime=null, FOriginSchemaId=null, FParentId=null;

insert into TsMenu set FId='4806684c-e000-3135-6003-1961e9cb7bc0', FParentId='21e2754a-d586-4bfa-bebe-768f70b9148b', FIndex=13, FTreeLevel=3, FTreeSerial='004.003.013', FName='聊天訊息彙整', FIcon='quicksilver/image/unit/New.gif', FType='InternalPage', FTabTitleSource='PageTitle', FTabTitle=null, FAlwaysOpenNewTab=null, FIsSystemLevel=0, FPageId='4806684c-e000-3135-6003-1961e9cb7a80', FQueryFormHidden=null, FQuerySchemaId=null, FQuerySchemaLocked=null, FArguments=null, FExternalPageUrl=null, FOpenMode='Tab', FFunctionName=null, FLicensed=1, FEnabled=1, FReplaceByChildren=0, FSubMenuSource='MenuTable', FSubMenuRoutine=null, FHideInMainMenu=null, FDigitEnabled=null, FDigitBold=null, FDigitColor=null, FDigitHandlerClassName=null, FBuiltin=0, FCountStatusField=null, FCountJavaClass=null, FShowMenuNameInTab=null, FCountStatus3=null, FCountStatus4=null, FCountStatus1=null, FCountStatus2=null, FCountType=null, FCountUserField=null, FEncrypt=null, FCountUnitId=null;

